### ISSUE TITLE
people_count_app.py

### ISSUE THREAD

**Issue by raylooi** [Akhtar303/Vehicle-Detection-and-Tracking-Usig-YOLO-and-Deep-Sort-with-Keras-and-Tensorflow#3]
Hi Akhtar, 

how do you use people_count_app.py ?

**Comment by Akhtar303** [comment]
@raylooi  it's just integration of  same code with Flask so just run python people_count_app.py and using any other Flask API or Postman  to hit '/People_Count' API  which define in people_count_app.py to give path of any video path or IP camera path.

**Comment by Akhtar303** [comment]
closed
